### ISSUE TITLE
Breaks with Unicode errors

### ISSUE THREAD

**Issue by framirez-bz** [jldiaz/mkdocs-plugin-tags#10]
Note sure what's causing this but the content on the page has no failures until I enabled this plugin again...

```
mkdocs serve --livereload
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 261, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tags/plugin.py", line 60, in on_files
    self.metadata.append(get_metadata(f.src_path, config["docs_dir"]))
  File "/usr/local/lib/python3.9/site-packages/tags/plugin.py", line 130, in get_metadata
    meta = yaml.load(metadata, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 243, in fetch_more_tokens
    return self.fetch_folded()
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 638, in fetch_folded
    self.fetch_block_scalar(style='>')
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 649, in fetch_block_scalar
    self.tokens.append(self.scan_block_scalar(style))
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 990, in scan_block_scalar
    self.scan_block_scalar_ignored_line(start_mark)
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 1101, in scan_block_scalar_ignored_line
    raise ScannerError("while scanning a block scalar", start_mark,
yaml.scanner.ScannerError: while scanning a block scalar
  in "<unicode string>", line 2, column 1:
    >         "owner": "owner_name",
    ^
expected a comment or a line break, but found '"'
  in "<unicode string>", line 2, column 11:
    >         "owner": "owner_name",
              ^
```

**Comment by jldiaz** [comment]
Despite the word "Unicode" showing up in the error message, I think the problem is not unicode related. Apparently the meta-data section of one of your documents contains invalid YAML syntax. 

The error is triggered at one line containing "owner": "owner_name", but probably it is caused by previous line (one comma missing, perhaps?). If you can find the file that causes the problem you could paste the metadata block, to see if it has something wrong.

**Comment by framirez-bz** [comment]
This the code block next to the lines in teh error, the rest of the content is internal only so I can't share but it's all just text with some code output.

```
<         "owner": "owner_name",
---
>         "owner": "owner_name",
```

I've tried commenting out the special characters, removing the line with `---` but then it shows this:

```markdown
    raise ScannerError("while scanning for the next token", None,
    yaml.scanner.ScannerError: while scanning for the next token
    found character '`' that cannot start any token
    in "<unicode string>", line 3, column 1:
    ```
```

**Comment by framirez-bz** [comment]
Found the issue...

Someone created a page with malformed for code blocks using four ` instead of three.  Took me all night and all morning but it seems to be working now.
