### ISSUE TITLE
Causes yaml parser error

### ISSUE THREAD

**Issue by jurgenhaas** [jldiaz/mkdocs-plugin-tags#9]
As soon as we enable this plugin we get parser errors:

```
mkdocs    | Installing python modules: fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-build-plantuml-plugin git+https://github.com/jldiaz/mkdocs-plugin-tags.git
mkdocs    | Modules installed.
mkdocs    | Detected previous installation in (/mkdocs).
mkdocs    | Starting MKDocs
mkdocs    | LIVE RELOAD - [ ENABLED ]
mkdocs    | FAST_MODE - [ ENABLED ]
mkdocs    | INFO    -  Building documentation... 
mkdocs    | WARNING -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead. 
mkdocs    | WARNING -  A 'dirty' build is being performed, this will likely lead to inaccurate navigation and other links within your site. This option is designed for site development purposes only. 
mkdocs    | Traceback (most recent call last):
mkdocs    |   File "/usr/bin/mkdocs", line 8, in <module>
mkdocs    |     sys.exit(cli())
mkdocs    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
mkdocs    |     return self.main(*args, **kwargs)
mkdocs    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
mkdocs    |     rv = self.invoke(ctx)
mkdocs    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
mkdocs    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
mkdocs    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
mkdocs    |     return ctx.invoke(self.callback, **ctx.params)
mkdocs    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
mkdocs    |     return callback(*args, **kwargs)
mkdocs    |   File "/usr/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
mkdocs    |     serve.serve(
mkdocs    |   File "/usr/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
mkdocs    |     config = builder()
mkdocs    |   File "/usr/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
mkdocs    |     build(config, live_server=live_server, dirty=dirty)
mkdocs    |   File "/usr/lib/python3.8/site-packages/mkdocs/commands/build.py", line 261, in build
mkdocs    |     files = config['plugins'].run_event('files', files, config=config)
mkdocs    |   File "/usr/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
mkdocs    |     result = method(item, **kwargs)
mkdocs    |   File "/usr/lib/python3.8/site-packages/tags/plugin.py", line 60, in on_files
mkdocs    |     self.metadata.append(get_metadata(f.src_path, config["docs_dir"]))
mkdocs    |   File "/usr/lib/python3.8/site-packages/tags/plugin.py", line 130, in get_metadata
mkdocs    |     meta = yaml.load(metadata, Loader=yaml.FullLoader)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
mkdocs    |     return loader.get_single_data()
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
mkdocs    |     node = self.get_single_node()
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
mkdocs    |     document = self.compose_document()
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
mkdocs    |     node = self.compose_node(None, None)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
mkdocs    |     node = self.compose_mapping_node(anchor)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
mkdocs    |     item_value = self.compose_node(node, item_key)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
mkdocs    |     node = self.compose_mapping_node(anchor)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
mkdocs    |     item_value = self.compose_node(node, item_key)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
mkdocs    |     node = self.compose_mapping_node(anchor)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
mkdocs    |     item_value = self.compose_node(node, item_key)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
mkdocs    |     node = self.compose_mapping_node(anchor)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
mkdocs    |     item_value = self.compose_node(node, item_key)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
mkdocs    |     node = self.compose_mapping_node(anchor)
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
mkdocs    |     while not self.check_event(MappingEndEvent):
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
mkdocs    |     self.current_event = self.state()
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
mkdocs    |     if self.check_token(KeyToken):
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
mkdocs    |     self.fetch_more_tokens()
mkdocs    |   File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
mkdocs    |     raise ScannerError("while scanning for the next token", None,
mkdocs    | yaml.scanner.ScannerError: while scanning for the next token
mkdocs    | found character '`' that cannot start any token
mkdocs    |   in "<unicode string>", line 15, column 1:
mkdocs    |     ```
mkdocs    |     ^
```

Looks like this tool can not co-exist with embedded code fragments on markdown pages.

**Comment by jurgenhaas** [comment]
Problem solved, it was in fact an issue with our markdown, we had one instance like this:

```
```shell script
$> ssh -T git@github.com
```
```

No idea where that came from. MkDocs doesn't complain about it but the tags plugin does. We've corrected `shell script` to `bash` and now tags are working just fine.
